name: import_sorter
description: Automatically organize your dart imports
version: 4.6.0
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  yaml: ^3.1.1
  path: ^1.8.2
  pre_commit_helpers:
    git:
      url: https://github.com/ReliableCauliflower/pre_commit_helpers