name: import_sorter
description: Automatically organize your dart imports
version: 4.6.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.3.1
  tint: ^2.0.0
  yaml: ^3.1.1
  path: ^1.8.2
